### ISSUE TITLE
bootstrap.sh not updated to include ffmpeg

### ISSUE THREAD

**Issue by TMeerhof** [openstate/open-cultuur-data#101]
bootstrap.sh does not include install for ffmpeg, also Cython needs to be installed first.

I think something like this should do the trick:

------
sudo easy_install -q pip

echo "Installing ffmpeg"
cd /vagrant
sudo ./install_pyav_deps.sh

virtualenv -q ocd
chown -R vagrant:vagrant ocd
echo "source /home/vagrant/ocd/bin/activate; cd /vagrant;" >> ~/.bashrc

echo "Installing requirements"
source ocd/bin/activate

pip install Cython==0.21.2 && pip install -r requirements.txt

echo "Starting"
./manage.py elasticsearch create_indexes /vagrant/es_mappings/
./manage.py elasticsearch put_template

----

**Comment by siccovansas** [comment]
This indeed seems to work (at least in Vagrant)!

I added `cd ~` and `cd /vagrant` to make sure that the virtualenv folder is located in `/home/vagrant/ocd`.

```
sudo easy_install -q pip

echo "Installing ffmpeg"
cd /vagrant
sudo ./install_pyav_deps.sh

cd ~
virtualenv -q ocd
chown -R vagrant:vagrant ocd
echo "source /home/vagrant/ocd/bin/activate; cd /vagrant;" >> ~/.bashrc

echo "Installing requirements"
source ocd/bin/activate

cd /vagrant
pip install Cython==0.21.2 && pip install -r requirements.txt

echo "Starting"
./manage.py elasticsearch create_indexes /vagrant/es_mappings/
./manage.py elasticsearch put_template
```
