### ISSUE TITLE
exact meaning of item.get_rights

### ISSUE THREAD

**Issue by coret** [openstate/open-cultuur-data#24]
All items have a function ```get_rights``` where you can declare the rights. But the rights of what exactly?

I'm currenty working on a dataset where the owner (on the datablog on Open Cultuur Data) states (translated): *"the metadata is CC0 licensed and the content is CC BY SA licensed"*

As OCD is storing the metadata I guess ```get_rights``` should return CC0. But how do we guard API users from showing the contents (eg. image referenced in metadata) without proper attribution? The easiest way is to let  ```get_rights``` return CC BY SA...

**Comment by breyten** [comment]
See also #28
