### ISSUE TITLE
Handle's from National Archive not working properly

### ISSUE THREAD

**Issue by ajslaghu** [openstate/open-cultuur-data#49]
http://search.opencultuurdata.nl/?q=Akte
(first picture, klik!). handlle error. Suggests html-url error.

**Comment by breyten** [comment]
This still gives an error : http://search.opencultuurdata.nl/?q=Akte#/object/nationaal_archief_beeldbank/a93ec6d6aba6d8331a6d38e98f7d6fdc990077f2

**Comment by timdehaan** [comment]
Thanx Breyten for the reminder,

I do have a partial solution. In the hierarchy of the archive the archive itself has a link in the API and the scans of an inventorynumber do have unique identifiers. However, the record itself - which holds for example 11 scans:

http://www.gahetna.nl/collectie/archief/inventaris/gahetnascans/eadid/1.01.02/inventarisnr/12631.2/level/file 

Doesn't have an unique handle. However the API is generating a not working, incorrect one.

I've asked if we could profide an unique id on the hierarchy-level of the record. But that could take some time. In between a solution could be referring to the photohandle:

![image](https://cloud.githubusercontent.com/assets/8033504/9326555/dd797f44-459a-11e5-96da-9db3dd2a9ead.png)

The only thing that needs to be changed then is the prefix. That doesn't work with:

hdl://10648/....

But is does resolve to the correct location with: 

http://hdl.handle.net/10648/....

**Comment by breyten** [comment]
Thanks for the quick fix @timdehaan !
