### ISSUE TITLE
No documentation for "Gemeente Ede"

### ISSUE THREAD

**Issue by bartdegoede** [openstate/open-cultuur-data#92]
There is a source available, called `gemeente_ede` (based on some static dump). There is no documentation available for this collection.

**Comment by breyten** [comment]
See https://github.com/openstate/open-cultuur-data/blob/dev/docs/user/datasets.rst#gemeentearchief-ede

**Comment by bartdegoede** [comment]
Oops, should have checked there too. Never mind then :)
